targets:
  debian-7: &debian
    build_dependencies:
      - libpam0g-dev
    dependencies:
      - libpam0g
      - git
  ubuntu-16.04:
    <<: *debian
before:
  - mv packager/Procfile .
  - mv packager/.godir .
after:
  - mv bin/main gogs
after_install: ./packager/hooks/postinst
